name: ar_quido
description: A Flutter plugin for handling image recognition on mobile platforms
version: 0.1.2
repository: https://github.com/miquido/ar_quido
issue_tracker: https://github.com/miquido/ar_quido/issues
homepage: https://github.com/miquido/ar_quido
documentation: https://pub.dev/documentation/ar_quido/latest/

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=3.3.10"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  stream_transform: ^2.1.0

dev_dependencies:
  async: 2.10.0
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter
  lint_quido: 0.4.0
  mockito: 5.3.2


flutter:
  plugin:
    platforms:
      android:
        package: com.miquido.ar_quido
        pluginClass: ARQuidoPlugin
      ios:
        pluginClass: ARQuidoPlugin
