name: Run tests and static checks

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  FLUTTER_VERSION: 3.19.6

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true
      - name: Restore packages
        run: flutter pub get
      - name: Generate required files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
  validate-for-pub:
    name: 'Perform dry run for pub.dev publish'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Publish - dry run
        run: dart pub publish --dry-run
